In [1]:
import numpy as np
import re
from bs4 import BeautifulSoup 
import requests

In [211]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

India = "https://www.espncricinfo.com/records/team/batting-most-runs-career/india-6/twenty20-internationals-3"
Australia ="https://www.espncricinfo.com/records/team/batting-most-runs-career/australia-2/test-matches-1"
Bangladesh="https://www.espncricinfo.com/records/team/batting-most-runs-career/bangladesh-25/test-matches-1"
England="https://www.espncricinfo.com/records/team/batting-most-runs-career/england-1/test-matches-1"
New_zealand="https://www.espncricinfo.com/records/team/batting-most-runs-career/new-zealand-5/test-matches-1"
Pakistan="https://www.espncricinfo.com/records/team/batting-most-runs-career/pakistan-7/test-matches-1"
South_africa="https://www.espncricinfo.com/records/team/batting-most-runs-career/south-africa-3/test-matches-1"
Srilanka="https://www.espncricinfo.com/records/team/batting-most-runs-career/sri-lanka-8/test-matches-1"
West_indies="https://www.espncricinfo.com/records/team/batting-most-runs-career/west-indies-4/test-matches-1"
Afghanistan="https://www.espncricinfo.com/records/team/batting-most-runs-career/afghanistan-40/test-matches-1" 

# headers = {
#     "User-Agent": "Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
# }

url=[India,Australia,Bangladesh,England,New_zealand,Pakistan,South_africa,Srilanka,West_indies,Afghanistan]
Country=[]
Player=[]
Span=[]
Matches=[]
Innings=[]
Not_Out=[]
Runs=[]
Highest_score=[]
Average=[]
Ball_Faced=[]
Strike_Rate=[]
Hundreds =[]
Fiftys=[]
Zeros=[]
Fours=[]
Sixes =[]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}
for x in range(len(url)):
    response = requests.get(url[x], headers=headers)
    print(response)
    soup=BeautifulSoup(response.text)
    x = soup.find_all("td",attrs={"class":"ds-min-w-max"})
    country=soup.find_all("span",attrs={"class":"ds-text-compact-xs ds-block ds-text-typo hover:ds-text-typo-primary"})

    n=0
    while n<len(x):
        Country.append(country[1].text.split()[0])
        Player.append(x[n].text)
        n+=1
        Span.append(x[n].text)
        n+=1
        Matches.append(x[n].text)
        n+=1
        Innings.append(x[n].text)
        n+=1
        Not_Out.append(x[n].text)
        n+=1
        Runs.append(x[n].text)
        n+=1
        Highest_score.append(x[n].text)
        n+=1
        Average.append(x[n].text)
        n+=1
        Ball_Faced.append(x[n].text)
        n+=1
        Strike_Rate.append(x[n].text)
        n+=1
        Hundreds.append(x[n].text)
        n+=1
        Fiftys.append(x[n].text)
        n+=1
        Zeros.append(x[n].text)
        n+=1
        Fours.append(x[n].text)
        n+=1
        Sixes.append(x[n].text)
        n+=1

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [213]:
len(Player)

1353

In [215]:
TEST={
"Country":Country,
"Player":Player,
"Span":Span,
"Matches":Matches,
"Innings":Innings,
"Not_Out":Not_Out,
"Runs":Runs,
"Highest_score":Highest_score,
"Average":Average,
"Ball_Faced":Ball_Faced,
"Strike_Rate":Strike_Rate,
"Hundreds":Hundreds,
"Fiftys":Fiftys,
"Zeros":Zeros,
"Fours":Fours,
"Sixes":Sixes,
}

In [217]:
df=pd.DataFrame(TEST)

In [219]:
df

,Country,Player,Span,Matches,Innings,Not_Out,Runs,Highest_score,Average,Ball_Faced,Strike_Rate,Hundreds,Fiftys,Zeros,Fours,Sixes
0,India,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
1,India,SR Tendulkar,1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
2,India,R Dravid,1996-2012,163,284,32,13265,270,52.63,31184,42.53,36,63,7,1651,21
3,India,SM Gavaskar,1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
4,India,V Kohli,2011-2025,123,210,13,9230,254*,46.85,16608,55.57,30,31,15,1027,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1348,Afghanistan,Bahir Shah,2023-2023,1,1,-,7,7,7.00,13,53.84,-,-,-,1,0
1349,Afghanistan,AM Ghazanfar,2024-2024,1,1,-,6,6,6.00,4,150.00,-,-,-,0,1
1350,Afghanistan,Sediqullah Atal,2024-2024,1,1,-,3,3,3.00,6,50.00,-,-,-,0,0
1351,Afghanistan,Mohammad Saleem,2024-2024,1,2,-,2,2,1.00,11,18.18,-,-,1,0,0
1352,Afghanistan,Waqar Salamkheil,2019-2019,1,1,1,1,1*,-,4,25.00,-,-,-,0,0

In [221]:
df.to_csv("TEST.csv")