In [2]:
import pandas as pd

In [4]:
import numpy as np
import re
from bs4 import BeautifulSoup 
import requests

In [116]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

India = "https://www.espncricinfo.com/records/team/batting-most-runs-career/india-6/one-day-internationals-2"
Australia ="https://www.espncricinfo.com/records/team/batting-most-runs-career/australia-2/one-day-internationals-2"
Bangladesh="https://www.espncricinfo.com/records/team/batting-most-runs-career/bangladesh-25/one-day-internationals-2"
England="https://www.espncricinfo.com/records/team/batting-most-runs-career/england-1/one-day-internationals-2"
New_zealand="https://www.espncricinfo.com/records/team/batting-most-runs-career/new-zealand-5/one-day-internationals-2"
Pakistan="https://www.espncricinfo.com/records/team/batting-most-runs-career/pakistan-7/one-day-internationals-2"
South_africa="https://www.espncricinfo.com/records/team/batting-most-runs-career/south-africa-3/one-day-internationals-2"
Srilanka="https://www.espncricinfo.com/records/team/batting-most-runs-career/sri-lanka-8/one-day-internationals-2"
West_indies="https://www.espncricinfo.com/records/team/batting-most-runs-career/west-indies-4/one-day-internationals-2"
Afghanistan="https://www.espncricinfo.com/records/team/batting-most-runs-career/afghanistan-40/one-day-internationals-2" 

# headers = {
#     "User-Agent": "Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
# }

url=[India,Australia,Bangladesh,England,New_zealand,Pakistan,South_africa,Srilanka,West_indies,Afghanistan]
Country=[]
Player=[]
Span=[]
Matches=[]
Innings=[]
Not_Out=[]
Runs=[]
Highest_score=[]
Average=[]
Ball_Faced=[]
Strike_Rate=[]
Hundreds =[]
Fiftys=[]
Zeros=[]
Fours=[]
Sixes =[]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}
for x in range(len(url)):
    response = requests.get(url[x], headers=headers)
    print(response)
    soup=BeautifulSoup(response.text)
    x = soup.find_all("td",attrs={"class":"ds-min-w-max"})
    country=soup.find_all("span",attrs={"class":"ds-text-compact-xs ds-block ds-text-typo hover:ds-text-typo-primary"})

    n=0
    while n<len(x):
        Country.append(country[1].text.split()[0])
        Player.append(x[n].text)
        n+=1
        Span.append(x[n].text)
        n+=1
        Matches.append(x[n].text)
        n+=1
        Innings.append(x[n].text)
        n+=1
        Not_Out.append(x[n].text)
        n+=1
        Runs.append(x[n].text)
        n+=1
        Highest_score.append(x[n].text)
        n+=1
        Average.append(x[n].text)
        n+=1
        Ball_Faced.append(x[n].text)
        n+=1
        Strike_Rate.append(x[n].text)
        n+=1
        Hundreds.append(x[n].text)
        n+=1
        Fiftys.append(x[n].text)
        n+=1
        Zeros.append(x[n].text)
        n+=1
        Fours.append(x[n].text)
        n+=1
        Sixes.append(x[n].text)
        n+=1

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [122]:
len(Country)

1406

In [124]:
ODI={
"Country":Country,
"Player":Player,
"Span":Span,
"Matches":Matches,
"Innings":Innings,
"Not_Out":Not_Out,
"Runs":Runs,
"Highest_score":Highest_score,
"Average":Average,
"Ball_Faced":Ball_Faced,
"Strike_Rate":Strike_Rate,
"Hundreds":Hundreds,
"Fiftys":Fiftys,
"Zeros":Zeros,
"Fours":Fours,
"Sixes":Sixes,
}

In [126]:
df=pd.DataFrame(ODI)

In [128]:
df.iloc[160]

Country          Australia
Player           ML Hayden
Span             1993-2008
Matches                160
Innings                154
Not_Out                 15
Runs                  6131
Highest_score         181*
Average              44.10
Ball_Faced            7762
Strike_Rate          78.98
Hundreds                10
Fiftys                  36
Zeros                    9
Fours                  636
Sixes                   87
Name: 160, dtype: object

In [143]:
df

,Country,Player,Span,Matches,Innings,Not_Out,Runs,Highest_score,Average,Ball_Faced,Strike_Rate,Hundreds,Fiftys,Zeros,Fours,Sixes
1,India,SR Tendulkar,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
2,India,V Kohli,2008-2025,302,290,45,14181,183,57.88,15192,93.34,51,74,16,1325,152
3,India,SC Ganguly,1992-2007,308,297,23,11221,183,40.95,15235,73.65,22,71,16,1104,189
4,India,RG Sharma,2007-2025,273,265,36,11168,264,48.76,12034,92.80,32,58,16,1045,344
5,India,R Dravid,1996-2011,340,314,39,10768,153,39.15,15127,71.18,12,82,13,942,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,Afghanistan,Najeeb Tarakai,2017-2017,1,1,-,5,5,5.00,18,27.77,-,-,-,0,0
1402,Afghanistan,Zia-ur-Rehman,2023-2023,1,1,-,5,5,5.00,30,16.66,-,-,-,1,0
1403,Afghanistan,Zakiullah Zaki,2012-2012,1,1,1,3,3*,-,22,13.63,-,-,-,0,0
1404,Afghanistan,Abdullah Mazari,2010-2010,2,1,-,3,3,3.00,16,18.75,-,-,-,0,0
1405,Afghanistan,Ahmed Shah,2009-2009,1,1,-,2,2,2.00,10,20.00,-,-,-,0,0

In [145]:
df.to_csv("ODI STAT.csv")

In [484]:
soup.find_all("h1",attrs={"class":"ds-text-title-m ds-font-bold ds-my-4"})

[]

In [486]:

response.text

'\n<html>\n   <body>\n      <script src="/eblN1L-yuK/zkQSn3Emn1/wzYE2ramOV/AnJVAQ/DH5-UWBy/AE0-AQ?v=a4bff242-4162-af9e-7e17-175c2352172d&t=75693476"></script>\n      <script>\n         (function() {\n             var chlgeId = \'\';\n             var scripts = document.getElementsByTagName(\'script\');\n             for (var i = 0; i < scripts.length; i++) {\n                 if (scripts[i].src && scripts[i].src.match(/t=([^&#]*)/)) {\n                     chlgeId = scripts[i].src.match(/t=([^&#]*)/)[1];\n                 }\n             }\n             var proxied = window.XMLHttpRequest.prototype.send;\n             window.XMLHttpRequest.prototype.send = function() {\n                 var pointer = this\n                 var intervalId = window.setInterval(function() {\n                     if (pointer.readyState === 4 && pointer.responseURL && pointer.responseURL.indexOf(\'t=\' + chlgeId) > -1) {\n                         location.reload(true);\n                         clearInterval(intervalId);\n                     }\n                 }, 1);\n                 return proxied.apply(this, [].slice.call(arguments));\n             };\n         })();\n      </script>\n   </body>\n</html>'

In [139]:

df.drop(index=0,axis=0,inplace=True)
df

,Country,Player,Span,Matches,Innings,Not_Out,Runs,Highest_score,Average,Ball_Faced,Strike_Rate,Hundreds,Fiftys,Zeros,Fours,Sixes
1,India,SR Tendulkar,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
2,India,V Kohli,2008-2025,302,290,45,14181,183,57.88,15192,93.34,51,74,16,1325,152
3,India,SC Ganguly,1992-2007,308,297,23,11221,183,40.95,15235,73.65,22,71,16,1104,189
4,India,RG Sharma,2007-2025,273,265,36,11168,264,48.76,12034,92.80,32,58,16,1045,344
5,India,R Dravid,1996-2011,340,314,39,10768,153,39.15,15127,71.18,12,82,13,942,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,Afghanistan,Najeeb Tarakai,2017-2017,1,1,-,5,5,5.00,18,27.77,-,-,-,0,0
1402,Afghanistan,Zia-ur-Rehman,2023-2023,1,1,-,5,5,5.00,30,16.66,-,-,-,1,0
1403,Afghanistan,Zakiullah Zaki,2012-2012,1,1,1,3,3*,-,22,13.63,-,-,-,0,0
1404,Afghanistan,Abdullah Mazari,2010-2010,2,1,-,3,3,3.00,16,18.75,-,-,-,0,0
1405,Afghanistan,Ahmed Shah,2009-2009,1,1,-,2,2,2.00,10,20.00,-,-,-,0,0

In [107]:
a=soup.find_all("span",attrs={"class":"ds-text-compact-xs ds-block ds-text-typo hover:ds-text-typo-primary"})

print(a[1].text.split()[0])

India

In [75]:
soup.text

'India ODI matches batting most runs career | ESPNcricinfoLive ScoresSeriesTeamsNewsFeaturesVideosStatsENG vs INDEdition INRecordsHome2025Ask CricinfoStatsguruIPLWorld CupWPLChampions TrophyMore RecordsIndia RecordsODI Matches RecordsBatting Most Runs Career Most runs for India in ODIs Most runsPlayerSpanMatInnsNORunsHSAveBFSR1005004s6sSR Tendulkar1989-20124634524118426200*44.832136886.234996202016195V Kohli2008-2025302290451418118357.881519293.345174161325152SC Ganguly1992-2007308297231122118340.951523573.652271161104189RG Sharma2007-2025273265361116826448.761203492.803258161045344R Dravid1996-2011340314391076815339.151512771.1812821394242MS Dhoni2004-20193472948310599183*50.231216487.1397310809222M Azharuddin1985-2000334308549378153*36.921266974.027589622+77+Yuvraj Singh2000-201730127539860915036.47984687.43145218896153V Sehwag1999-20132412359799521935.377655104.441537141092131S Dhawan2010-202216716410679314344.11743691.351739584279SK Raina2005-2018226194355615116*35.31600593.5053614476120A Jadeja1992-200019617936535911937.47767869.796301036685G Gambhir2003-2013147143115238150*39.68614485.2511341156117NS Sidhu1987-199813612784413134*37.08632969.72633733544K Srikkanth1981-19921461454409112329.01570271.7442711405+41+N Kapil Dev1978-1994225198393783175*23.79397995.0711413291+67+DB Vengsarkar1976-199112912019350810534.73517967.731237228+24+RJ Shastri1981-199215012821310810929.04508961.074185206+25+SM Gavaskar1974-1987108102143092103*35.13496662.261278234+21+KL Rahul2016-2025857917304311249.08345188.17718323567AM Rahane2011-201890873296211135.26376778.63324629333SS Iyer2017-2025706562845128*48.222845100.00522126272RA Jadeja2009-20252041375128068732.62328485.44-13620554Shubman Gill2019-202555558277520859.04278799.56815131359M Kaif2002-2006125110242753111*32.01382272.0321782289VG Kambli1991-20001049721247710632.59344371.94214418720VVS Laxman1998-200686837233813130.76328271.2361032224RR Singh1989-200113611323233610025.95314474.30195135+41+SV Manjrekar1988-1996747010199410533.23310164.3011539910M Amarnath1975-19898575121924102*30.53333457.702132123+9+HH Pandya2016-2025946810190492*32.821717110.89-11414176M Prabhakar1984-19961309821185810624.12308360.262118157+0+KD Karthik2004-201994792117527930.20239273.24-9617615AT Rayudu2013-20195550141694124*47.05214379.04310314530IK Pathan2004-2012120872115448323.39194179.54-5714237KM Jadhav2014-2020735219138912042.091367101.6026214124NR Mongia1994-2000140963312726920.19184568.94-24958AB Agarkar1998-20071911132612699514.58157480.62-31010322D Mongia2001-2007575171230159*27.95172171.471441228Harbhajan Singh1998-20152341263512134913.32150280.75--179034SM Patil1980-19864542110058424.51122382.17-9474+12+RV Uthappa2006-2015464269348625.94103190.59-6410719Ishan Kishan2021-20232724293321042.40913102.191719533A Kumble1990-2007269134479032610.37148160.97--18526Yashpal Sharma1978-1985424098838928.48140163.02-4-52+10+J Srinath1991-2003229121388835310.63110979.62-1196217RR Pant2018-202431271871125*33.50820106.211539126HK Badani2000-200440361086710033.34118073.471416810YK Pathan2008-2012574111810123*27.00713113.602376243R Lamba1986-19893231278310227.00116667.1516263+9+AR Patel2014-202568471278364*22.3785691.47-334531SA Yadav2021-20233735577372*25.76736105.02-438019Z Khan2000-2012194963175334*11.58104172.33--146524PA Patel2003-2012383437369523.7496276.50-42797R Ashwin2010-202311663207076516.4481386.96-16607S Ramesh1999-1999242416468228.08109259.15-63701RMH Binny1980-19877249106295716.12104660.13-1451+1+WV Raman1988-19962727161711423.73110955.63136475SB Joshi1996-200169451158461*17.1765389.43-144717MK Pandey2015-202129247566104*33.2962590.56122455KS More1984-199394652256342*13.0980869.67--543+4+B Kumar2012-2022121551655253*14.1574773.89-18468PK Amre1991-19943730551384*20.5279964.20-21282SV Samson2021-20231614551010856.6651299.6013-3422AO Malhotra1982-1986201944576530.4664570.85-1-29+1+C Sharma1983-1994653516456101*24.0050490.471-3314GR Viswanath1974-1982252314397519.9583052.89-2133+0+AK Sharma1988-19933127642459*20.1946990.40-3226+9+S Madan Lal1974-198767351440153*19.0964562.17-1125+3+SMH Kirmani1976-198649311337348*20.7261660.55--224+0+SS Karim1997-2000342743625515.7356064.64-12272M Vijay2010-20151716-3397221.1850666.99-1-333HH Kanitkar1997-2000342783395717.8451266.21-12251Washington Sundar2017-2025231513295123.5039483.50-1-2410SN Thakur2017-20234725632950*17.31313105.11-11319N Chopra1998-2000392663106115.5049862.24-11155P Kumar2007-201268331229254*13.9033188.21-12257CS Pandit1986-19923623929033*20.7140072.50--216+0+MK Tiwary2008-201512121287104*26.0940371.2111-243RS Sodhi2000-2002181432806725.4538173.49-2-166AD Gaekwad1975-19871514126978*20.6950952.84-1215+0+KBJ Azad1980-19862521226939*14.1540067.25--319+9+SS Dighe2000-20012317625694*23.2742160.80-11112BP Patel1974-197910912438230.3739960.90-1-22+3+STR Binny2014-2015141132307728.7524693.49-11235Mohammed Shami2013-20251084920225257.7527382.41--6179V Shankar2019-201912812234631.8524690.65---204BKV Prasad1994-20011616331221196.9036760.21--875Y Venugopal Rao2005-20061611221861*24.2236360.05-12163V Dahiya2000-2001191522165116.6126780.89-12183Kuldeep Yadav2017-20251134221207199.8540750.85--3140DL Chahar2018-2022139320369*33.8320798.06-21178V Rathour1996-199777-1935427.5733158.30-2-161PP Shaw2020-202166-1894931.50166113.85---322SB Bangar2002-20041515218057*13.8423975.31-13143SC Khanna1979-1984101021765622.0026566.41-21162GAHM Parkar1982-1984101011654218.3333249.69---11+0+RR Powar2004-2007311951635411.6426062.69-1-122JJ Martin1999-200110811583922.5733147.73--1150AC Bedade1994-1994131031585122.5718386.33-1-115CPS Chauhan1978-198177-1534621.8530150.83---6+0+DJ Hooda2022-202210711533325.5018980.95---101RS Gavaskar2004-2004111021515418.8723464.52-1-82AR Khurasiya1999-20011211-1495713.5418879.25-11142A Nehra2001-20111174521140245.8324457.37--9123R Vijay Bharadwaj1999-2002109413641*27.2019470.10--1151RK Chauhan1993-1997351851323210.1517177.19--454MSK Prasad1998-1999171121316314.5522558.22-12110KH Pandya2021-202154213058*65.00128101.56-1-112B Sai Sudharsan2023-20233311276263.5014289.43-2-171M Kartik2002-20073714512632*14.0017870.78--1101J Arun Lal1982-19891313-122519.3823252.58-14101L Balaji2002-20093016612021*12.0015278.94--283V Yadav1992-19941912211834*11.80116101.72--272Arshad Ayub1987-19903217711631*11.6016271.60--160GK Khoda1998-199822-1158957.5018562.16-1-110RD Gaikwad2022-202366-1157119.1615773.24-1-160FM Engineer1974-197554111454*38.0019558.46-1-130KD Ghavri1975-1981191661142011.4019458.76--18+0+NA Saini2019-20218531074553.5013778.10---93RP Singh2005-20115820101042310.4024242.97--351S Amarnath1978-197833-1006233.3311984.03-1-4+0+S Abid Ali1974-197553-937031.0013270.45-1-61JJ Bumrah2016-202389261491167.5815957.23--5101A Ratra2002-20021281903012.8512770.86---80VB Chandrasekhar1988-199077-885312.5716254.32-1-110MA Agarwal2020-202055-863217.2083103.61---121R Vinay Kumar2010-2013311348627*9.5514658.90--252S Sriram2000-2004871815713.5013560.00-1190Jai P Yadav2002-20051273816920.2512365.85-12111SK Sharma1988-199023124802810.0013559.25--240S Badrinath2008-20117617927*15.8017245.93---40UT Yadav2010-20187524147918*7.9013458.95--481YS Chahal2016-2023721457718*8.5514154.60--180MM Patel2006-201170271674156.7211266.07--471AL Wadekar1974-197422-736736.509081.11-1-110S Viswanath1985-1988221247223*9.0013951.79---50I Sharma2007-201680281372134.8020335.46--560NT Tilak Varma2023-2023441685222.6611957.14-1-61FY Fazal2016-20161115555*-6190.16-1-71RK Singh2023-202322-553827.5041134.14---53Mohammed Siraj2019-2024441710559*7.8512942.63--130JV Paranjpe1998-1998441542718.009159.34---31S Venkataraghavan1974-198315945426*10.8012642.85--230A Mithun2010-201153-512417.005592.72---24D Dasgupta2001-20015415124*17.008262.19--160CA Pujara2013-201455-512710.2013039.23--240BS Sandhu1982-198422735116*12.759752.57--22+1+SS Tiwary2010-20103224937*-5687.50---51DJ Gandhi1999-200033-493016.339750.51---80Adjust:Most recentPast weekPast MonthPast year4 years10 years25 years Records includes the following current or recent matches:Kenya vs England at Gros Islet, ICC World Cup 23rd Match, Group C, Mar 24, 2007 [ODI # 2553]New Zealand vs Kenya at Gros Islet, ICC World Cup 14th Match, Group C, Mar 20, 2007 [ODI # 2544]Canada vs Kenya at Gros Islet, ICC World Cup 3rd Match, Group C, Mar 14, 2007 [ODI # 2533]Terms of Use|Privacy Policy|Interest-Based Ads|Addendum to the Global Privacy Policy|Feedback© 2025 ESPN Sports Media Ltd. All rights reserved'